Repository Alpha-Damyo/BE, pull requests merged in 2024-08, with the labels that each got.

#100 Fix/#96 naver user info fetch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-deploy.yml
  README.md
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/global/config/SwaggerConfig.java
Labels: 개선, 우선순위 - 중, 버그 수정

#102 Refactor/#97 area simple tag
  src/main/java/com/damyo/alpha/api/info/controller/dto/InfoResponse.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/info/domain/Info.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchLocateRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchQueryRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaCustomRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
Labels: 개선, 우선순위 - 상

#103 Feature/#101 smoking area report
  src/main/java/com/damyo/alpha/api/report/domain/Report.java
  src/main/java/com/damyo/alpha/api/report/domain/ReportRepository.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportErrorCode.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportException.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
Labels: 기능 구현, 우선순위 - 상

#104 Refactor/#98 image upload spring
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
Labels: 개선, 우선순위 - 중

#110 Feature/#106 refresh token
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/ReissueRequest.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/TokenResponse.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/auth/exception/TokenException.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtProvider.java
  src/main/java/com/damyo/alpha/api/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/report/domain/Report.java
  src/main/java/com/damyo/alpha/api/report/domain/ReportRepository.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportErrorCode.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportException.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/exception/AreaErrorCode.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: PR

#113 #107 비활성화 태그 검색/통계 제외 +#108 서버 로깅 전체 적용 + #112 기본 프로필 사진 설정
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/auth/service/UserDetailServiceImpl.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/InfoResponse.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/info/domain/Info.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/picture/service/S3ImageService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/domain/SmokingDataRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/SshDataSourceConfig.java
  src/main/java/com/damyo/alpha/global/config/SshTunnelingInitializer.java
  src/main/resources/application.yml
Labels: PR

#114 Main Merge
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/ReissueRequest.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/TokenResponse.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/auth/exception/TokenException.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtProvider.java
  src/main/java/com/damyo/alpha/api/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/auth/service/UserDetailServiceImpl.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/InfoResponse.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/info/domain/Info.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/picture/service/S3ImageService.java
  src/main/java/com/damyo/alpha/api/report/domain/Report.java
  src/main/java/com/damyo/alpha/api/report/domain/ReportRepository.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportErrorCode.java
  src/main/java/com/damyo/alpha/api/report/exception/ReportException.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/exception/AreaErrorCode.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/domain/SmokingDataRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/java/com/damyo/alpha/global/config/SshDataSourceConfig.java
  src/main/java/com/damyo/alpha/global/config/SshTunnelingInitializer.java
  src/main/resources/application.yml
Labels: PR

#115 fix: 로그 추가 핫픽스
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
Labels: 핫픽스, PR

#116 merge to main
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtProvider.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 핫픽스, PR

#117 Feature/#111 api rate limiter
  build.gradle
  src/main/java/com/damyo/alpha/global/config/Bucket4jConfig.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/java/com/damyo/alpha/global/limiter/RateLimitFilter.java
  src/main/resources/application.yml
Labels: PR

#119 Main Merge
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/global/config/Bucket4jConfig.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/java/com/damyo/alpha/global/config/SwaggerConfig.java
  src/main/java/com/damyo/alpha/global/limiter/RateLimitFilter.java
  src/main/resources/application.yml
Labels: PR

#121 Main Merge
  src/main/java/com/damyo/alpha/global/config/SwaggerConfig.java
Labels: PR

#122 Main Merge
  src/main/java/com/damyo/alpha/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: PR

#123 Feature/#118 Redis를 활용한 흡연구역 / 사진 정보 캐싱 + #120 리뷰 별점이 흡연구역 별점에 반영 안되는 버그 수정
  build.gradle
  src/main/java/com/damyo/alpha/AlphaApplication.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureResponse.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/main/java/com/damyo/alpha/global/config/RedisCacheConfig.java
Labels: 기능 구현, 우선순위 - 하, 버그 수정

#124 merge to main
  build.gradle
  src/main/java/com/damyo/alpha/AlphaApplication.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureResponse.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/main/java/com/damyo/alpha/global/config/RedisCacheConfig.java
Labels: PR

#125 Feature/#101 smoking area report
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaReportDetail.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaReportDetailRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/ReportRequest.java
Labels: 개선, 우선순위 - 하, PR

#127 merge to main
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaReportDetail.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaReportDetailRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/ReportRequest.java
Labels: PR

#128 refactor: 200OK json으로 응답변경
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthException.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/picture/exception/PictureErrorCode.java
  src/main/java/com/damyo/alpha/api/picture/exception/PictureException.java
  src/main/java/com/damyo/alpha/api/picture/exception/S3ErrorCode.java
  src/main/java/com/damyo/alpha/api/picture/exception/S3Exception.java
  src/main/java/com/damyo/alpha/api/smokingarea/exception/AreaErrorCode.java
  src/main/java/com/damyo/alpha/api/smokingarea/exception/AreaException.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/star/exception/StarErrorCode.java
  src/main/java/com/damyo/alpha/api/star/exception/StarException.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/exception/UserErrorCode.java
  src/main/java/com/damyo/alpha/api/user/exception/UserException.java
  src/main/java/com/damyo/alpha/global/limiter/RateLimitFilter.java
  src/main/java/com/damyo/alpha/global/response/CommonSuccessApiResponse.java
  src/main/java/com/damyo/alpha/global/response/exception/error/BaseException.java
  src/main/java/com/damyo/alpha/global/response/exception/error/CommonErrorCode.java
  src/main/java/com/damyo/alpha/global/response/exception/error/ErrorCode.java
  src/main/java/com/damyo/alpha/global/response/exception/error/ErrorResponse.java
  src/main/java/com/damyo/alpha/global/response/exception/handler/GlobalExceptionHandler.java
Labels: 개선, PR

#129 Main Merge
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
Labels: PR
