Repository Alpha-Damyo/BE, pull requests merged in 2024-05, with the labels that each got.

#51 Feature/statistics 통계 관련 기능 구현
  src/main/java/com/damyo/alpha/AlphaApplication.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchLocateRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AllRegionStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AreaTopResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DailyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DayOfWeekStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/HourlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/MonthlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataRequest.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/StaticsDateResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/StaticsRegionResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/StatisticsDateResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/StatisticsRegionResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/WeeklyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/domain/SmokingDataRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
Labels: 기능 구현, 우선순위 - 상

#52 feature/image-filter requirements.txt add
  face_detect/requirements.txt
Labels: 핫픽스, 배포

#55 fix: 오타 수정
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchLocateRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchQueryRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
Labels: 핫픽스

#61 #47 QueryDSL 페이지네이션 적용 + #57 Swagger 적용 + API 명세 요구사항에 맞추어 엔드포인트 수정
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/challenge/controller/ChallengeController.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureSliceResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaListRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaListResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaSummaryResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/test/java/com/damyo/alpha/repository/PictureRepositoryTest.java
  src/test/java/com/damyo/alpha/repository/SmokingAreaRepositoryTest.java
Labels: 기능 구현, 우선순위 - 상

#63 merge to main
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/LoginRequest.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/SignUpRequest.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/TokenResponse.java
  src/main/java/com/damyo/alpha/api/auth/domain/UserDetailsImpl.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/challenge/controller/ChallengeController.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureSliceResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/exception/PictureErrorCode.java
  src/main/java/com/damyo/alpha/api/picture/exception/PictureException.java
  src/main/java/com/damyo/alpha/api/picture/exception/S3ErrorCode.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaListRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaListResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaSummaryResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/exception/AreaErrorCode.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/star/controller/StarController.java
  src/main/java/com/damyo/alpha/api/star/controller/dto/AddStarRequest.java
  src/main/java/com/damyo/alpha/api/star/controller/dto/StarResponse.java
  src/main/java/com/damyo/alpha/api/star/domain/Star.java
  src/main/java/com/damyo/alpha/api/star/exception/StarErrorCode.java
  src/main/java/com/damyo/alpha/api/star/service/StarService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UpdateUserNameRequest.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UpdateUserProfileRequest.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UpdateUserScoreRequest.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UserResponse.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/domain/UserRepository.java
  src/main/java/com/damyo/alpha/api/user/exception/UserErrorCode.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/JPAConfig.java
  src/main/java/com/damyo/alpha/global/exception/error/CommonErrorCode.java
  src/main/java/com/damyo/alpha/global/exception/error/ErrorCode.java
  src/main/java/com/damyo/alpha/global/exception/error/ErrorResponse.java
  src/test/java/com/damyo/alpha/repository/PictureRepositoryTest.java
  src/test/java/com/damyo/alpha/repository/SmokingAreaRepositoryTest.java
Labels: 기능 구현, 우선순위 - 상, 배포

#64 refactor: 실제 연동시 발생하는 버그 수정
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/resources/application.yml
Labels: 핫픽스, 우선순위 - 상

#65 merge to develop
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/SignUpRequest.java
  src/main/java/com/damyo/alpha/api/auth/domain/UserDetailsImpl.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/WebConfig.java
  src/main/java/com/damyo/alpha/global/coverter/OctetStreamReadMsgConverter.java
  src/main/resources/application.yml
Labels: 개선, 우선순위 - 상

#66 API 연결을 위한 버그 수정 및 비즈니스 로직 리팩토링
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchLocateRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchQueryRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaCustomRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AllRegionStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DailyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DayOfWeekStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/HourlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/MonthlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/WeeklyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
Labels: 개선, 우선순위 - 상

#67 메인 병합
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/SignUpRequest.java
  src/main/java/com/damyo/alpha/api/auth/domain/UserDetailsImpl.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/picture/controller/PictureController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchLocateRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SearchQueryRequest.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaCustomRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AllRegionStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DailyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/DayOfWeekStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/HourlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/MonthlyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/WeeklyStatisticsResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/WebConfig.java
  src/main/java/com/damyo/alpha/global/coverter/OctetStreamReadMsgConverter.java
  src/main/resources/application.yml
Labels: 배포

#68 refactor: 생성날짜 서버측정 및 DTO 수정
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataListRequest.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataRequest.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
Labels: 핫픽스

#69 메인 병합
  src/main/java/com/damyo/alpha/api/smokingdata/controller/SmokingDataController.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataListRequest.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/SmokingDataRequest.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
Labels: 배포
