Repository Alpha-Damyo/BE, pull requests merged in 2024-06, with the labels that each got.

#70 Feature/like count
  build.gradle
  docker-compose.yml
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestCustomRepository.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestLike.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestRepository.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/contest/service/ContestService.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/Picture.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AreaTopResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 기능 구현, 우선순위 - 중

#71 Feature/like count
  build.gradle
  docker-compose.yml
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestCustomRepository.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestLike.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestRepository.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/contest/service/ContestService.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/Picture.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingArea.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/controller/dto/AreaTopResponse.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 기능 구현, 우선순위 - 중

#75 merge to main
  build.gradle
  src/main/java/com/damyo/alpha/AlphaApplication.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/contest/domain/ContestContributionInfo.java
  src/main/java/com/damyo/alpha/api/contest/service/ContestService.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/info/domain/Info.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/domain/Picture.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepository.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/service/SmokingAreaService.java
  src/main/java/com/damyo/alpha/api/user/controller/UserController.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UserResponse.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/domain/UserRepository.java
  src/main/java/com/damyo/alpha/api/user/service/UserService.java
  src/main/java/com/damyo/alpha/global/config/JobConfig.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 우선순위 - 상, 배포

#76 Refactor/api connect API 버그 수정 및 기능 추가 구현
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/InfoResponse.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/smokingdata/domain/SmokingDataRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
Labels: 개선, 우선순위 - 중

#77 Main merge
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/InfoResponse.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaDetailResponse.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/smokingdata/domain/SmokingDataRepository.java
  src/main/java/com/damyo/alpha/api/smokingdata/service/SmokingDataService.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
Labels: 배포

#78 Refactor/api connect
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/AllRankResponse.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/LikesRankResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
Labels: 개선, 기능 구현, 우선순위 - 상

#79 Develop
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/AllRankResponse.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/LikesRankResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureCustomRepository.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
  src/main/java/com/damyo/alpha/api/smokingarea/domain/SmokingAreaRepositoryImpl.java
Labels: 배포

#81 Main mearge
  src/main/java/com/damyo/alpha/api/info/controller/InfoController.java
  src/main/java/com/damyo/alpha/api/info/controller/dto/UpdateInfoRequest.java
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
Labels: 배포

#83 merge to main
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtAuthenticationFilter.java
Labels: 핫픽스, 배포

#84 Main merge
  src/main/java/com/damyo/alpha/api/picture/controller/dto/ContestResponse.java
  src/main/java/com/damyo/alpha/api/picture/controller/dto/PictureSliceResponse.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
Labels: 배포

#85 Main merge
  src/main/java/com/damyo/alpha/api/info/service/InfoService.java
  src/main/java/com/damyo/alpha/api/picture/service/PictureService.java
Labels: 핫픽스, 배포

#86 Main merge
  src/main/java/com/damyo/alpha/api/smokingarea/controller/SmokingAreaController.java
  src/main/java/com/damyo/alpha/api/smokingarea/controller/dto/SmokingAreaAllResponse.java
Labels: 핫픽스, 배포

#87 merge to develop
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/SignUpRequest.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/auth/exception/TokenException.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtProvider.java
  src/main/java/com/damyo/alpha/api/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/auth/service/UserDetailServiceImpl.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UserResponse.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/domain/UserRepository.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/java/com/damyo/alpha/global/config/WebConfig.java
  src/main/java/com/damyo/alpha/global/converter/OctetStreamReadMsgConverter.java
  src/main/java/com/damyo/alpha/global/exception/error/CommonErrorCode.java
  src/main/java/com/damyo/alpha/global/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 개선

#88 merge to main
  build.gradle
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/controller/dto/SignUpRequest.java
  src/main/java/com/damyo/alpha/api/auth/exception/AuthErrorCode.java
  src/main/java/com/damyo/alpha/api/auth/exception/TokenException.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/damyo/alpha/api/auth/jwt/JwtProvider.java
  src/main/java/com/damyo/alpha/api/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
  src/main/java/com/damyo/alpha/api/auth/service/UserDetailServiceImpl.java
  src/main/java/com/damyo/alpha/api/user/controller/dto/UserResponse.java
  src/main/java/com/damyo/alpha/api/user/domain/User.java
  src/main/java/com/damyo/alpha/api/user/domain/UserRepository.java
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
  src/main/java/com/damyo/alpha/global/config/WebConfig.java
  src/main/java/com/damyo/alpha/global/converter/OctetStreamReadMsgConverter.java
  src/main/java/com/damyo/alpha/global/exception/error/CommonErrorCode.java
  src/main/java/com/damyo/alpha/global/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: 배포

#89 merge to main
  src/main/java/com/damyo/alpha/global/config/SecurityConfig.java
Labels: 핫픽스, 배포

#90 Main merge
  src/main/java/com/damyo/alpha/api/contest/controller/ContestController.java
  src/main/java/com/damyo/alpha/api/picture/domain/PictureRepositoryImpl.java
Labels: 배포

#91 Main merge
  src/main/java/com/damyo/alpha/api/picture/service/S3ImageService.java
Labels: 배포

#92 Main merge
  src/main/resources/application.yml
Labels: 배포

#93 Main merge
  src/main/java/com/damyo/alpha/api/picture/service/S3ImageService.java
Labels: 배포

#94 fix: 로깅을 위한 주석 처리
  src/main/java/com/damyo/alpha/api/auth/controller/AuthController.java
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
Labels: 핫픽스, 배포

#95 fix: 주석 제거
  src/main/java/com/damyo/alpha/api/auth/service/AuthService.java
Labels: 핫픽스, 배포
